version: "3.7"
services:
    frontend:
        build:
            context: docker/nginx
        ports:
            - "8080:80"
        depends_on:
          - frontend-node
    frontend-node:
        build:
            context: docker/node
        volumes:
            - ./frontend:/app
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run serve"
        tty: true
        environment:
            BACKEND_URL: http:localhost:8081
    frontend-node-cli:
        build:
            context: docker/node
        volumes:
            - ./frontend:/app
    backend:
        build:
            context: backend
        ports:
          - "8081:5000"
        volumes:
          - ./backend:/app
        environment:
          FLASK_ENV: development
